name: Release
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Print package.json
        run: cat ./package.json
      - name: Automated Version Bump
        id: versioning
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tagged version
        run: echo "${{ steps.versioning.outputs.newTag }}"
    outputs:
      new_tag: ${{ steps.versioning.outputs.newTag }}

  release:
    name: Release production
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Install libpcsclite-dev
        run: |
          sudo apt install -y libpcsclite-dev
      - name: Checking out tagged version
        run: echo "${{ needs.bump_version.outputs.new_tag }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump_version.outputs.new_tag }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run test -- --coverage --no-watch
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
